// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2uZcvqw7yn4Kz6HvzknhjnS-vhPTujIM',
    appId: '1:694372241770:web:b3437a6441da0f96fbd513',
    messagingSenderId: '694372241770',
    projectId: 'fir-c27c8',
    authDomain: 'fir-c27c8.firebaseapp.com',
    storageBucket: 'fir-c27c8.appspot.com',
    measurementId: 'G-92GDQHNZNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSI49yXXTGbJHtHBkMXNmrYCopkcwBpzw',
    appId: '1:694372241770:android:4b4d2ab93631bde2fbd513',
    messagingSenderId: '694372241770',
    projectId: 'fir-c27c8',
    storageBucket: 'fir-c27c8.appspot.com',
  );
}
